services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      APP_NAME: KeyLedger
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: "base64:YgBs7PrUgmEkbHc/BIOYdQl6rUw09srqJ8w0RMOF/1s="
      APP_URL: http://localhost:8000
      ADMIN_TOKEN: secret
      RUN_SEED: "true"
      LOG_CHANNEL: stderr
      DB_CONNECTION: sqlite
      PORT: "8000"
    volumes:
      # БД переживает перезапуск контейнера
      - sqlite_data:/var/www/html/database
    restart: unless-stopped

volumes:
  sqlite_data:
